@tool
extends RefCounted
## One small lookup table for the whole plugin: English text in, the
## current language out. Only what is shown is translated - everything
## saved in a graph stays English.

const ENGLISH := "English"
const SWEDISH := "Swedish"
const LANGUAGES := [ENGLISH, SWEDISH]

static var language := ENGLISH

const SV := {
	# Toolbar and panels
	"Attach to Selected Node": "Koppla till vald nod",
	"\u2715  Remove from Selected Node": "\u2715  Ta bort från vald nod",
	"Save Graph": "Spara graf",
	"Language": "Språk",
	"English": "Engelska",
	"Swedish": "Svenska",
	"Node Graph": "Nodgraf",
	"Scene Library": "Scenbibliotek",
	"Node Library": "Nodbibliotek",
	"all nodes": "alla noder",
	"attach Visuract to use these": "koppla Visuract för att använda dessa",
	"for %s": "för %s",
	"Visuract Scene Library": "Visuracts scenbibliotek",
	"Drag a scene onto a node in the Scene dock.": "Dra en scen till en nod i scenpanelen.",
	"No scenes yet - save some into %s": "Inga scener än - spara några i %s",
	"Comes with a Visuract script.": "Kommer med ett Visuract-skript.",
	"Play": "Spela",
	"Hello there!": "Hej där!",

	# Menus
	"Copy": "Kopiera",
	"Duplicate": "Duplicera",
	"Delete": "Ta bort",
	"Paste": "Klistra in",
	"Add Note": "Lägg till lapp",
	"Add %s": "Lägg till %s",
	"Note": "Lapp",
	"Write a note\u2026": "Skriv en lapp\u2026",
	"Double-click to edit this note. Drag an edge to resize it.": "Dubbelklicka för att skriva på lappen. Dra i en kant för att ändra storlek.",

	# Status messages
	"No node attached.": "Ingen nod kopplad.",
	"Select a node in the scene.": "Välj en nod i scenen.",
	"Select a node in the scene first.": "Välj en nod i scenen först.",
	"Showing: %s  (%d blocks)": "Visar: %s  (%d block)",
	"%s  \u26a0 overrides %s - revert Graph in the Inspector": "%s  \u26a0 åsidosätter %s - återställ Graph i Inspektorn",
	"%s has no Visuract script yet.": "%s har inget Visuract-skript än.",
	"Copied %d blocks - select another node and paste.": "Kopierade %d block - välj en annan nod och klistra in.",
	"Attach Visuract to %s first - then you can add blocks.": "Koppla Visuract till %s först - sedan kan du lägga till block.",
	"Attach Visuract to a node first - then you can add notes.": "Koppla Visuract till en nod först - sedan kan du lägga till lappar.",
	"Attach to a node first.": "Koppla till en nod först.",
	"a node": "en nod",
	"Will remove from": "Tar bort från",
	"Will attach to": "Kopplar till",
	"%s:  %s  (%s)": "%s:  %s  (%s)",
	"Attached to: %s": "Kopplad till: %s",
	"Removed Visuract from %s": "Tog bort Visuract från %s",
	"Saved %d nodes to %s": "Sparade %d noder till %s",
	"Save failed (%d): %s": "Sparandet misslyckades (%d): %s",
	"%s is an instanced scene - open %s to change it.": "%s är en instansierad scen - öppna %s för att ändra den.",
	"Remove Visuract": "Ta bort Visuract",
	"Remove": "Ta bort",
	"Remove Visuract from %s?\n\nIts %d blocks will be forgotten.": "Ta bort Visuract från %s?\n\nDess %d block glöms bort.",
	"Click Attach to Selected Node first.": "Klicka på Koppla till vald nod först.",
	"Needs a %s under %s before this can work.": "Behöver en %s under %s för att fungera.",
	"'%s' is not a Visuract node any more. Delete it and pick the closest one from the library.": "'%s' är inte en Visuract-nod längre. Ta bort den och välj den närmaste i biblioteket.",
	"Code:": "Kod:",

	# Fields
	"Pick a node": "Välj en nod",
	"Pick a file": "Välj en fil",
	"(this node)": "(den här noden)",
	"The node this script is on": "Noden som skriptet sitter på",
	"(nothing available)": "(inget tillgängligt)",
	"(none)": "(ingen)",
	"(what touched me)": "(det som rörde mig)",
	"(no input actions yet)": "(inga inmatningsåtgärder än)",
	"(no signal names yet)": "(inga signalnamn än)",
	"(no animations found)": "(inga animationer hittades)",
	"(nothing remembered yet)": "(inget ihågkommet än)",
	"Click to add a color, drag to move, click a handle to change it, right-click to remove.": "Klicka för att lägga till en färg, dra för att flytta, klicka på ett handtag för att ändra, högerklicka för att ta bort.",
	"+ Add Scene": "+ Lägg till scen",
	"Scene %d": "Scen %d",
	"Where": "Var",
	"Spawn Point": "Skapapunkt",
	"Chance": "Chans",
	"Offset": "Förskjutning",
	"Higher is more likely. 0 never spawns.": "Högre är mer troligt. 0 skapas aldrig.",
	"Edit Dialogue\u2026": "Redigera dialog\u2026",

	# Dialogue editor
	"Dialogue": "Dialog",
	"Style\u2026": "Stil\u2026",
	"Done": "Klar",
	"Show Preview": "Visa förhandsvisning",
	"Pick a Label on the Dialogue node first.": "Välj en Label på Dialog-noden först.",
	"DEFAULT RESPONSES": "STANDARDSVAR",
	"Cycled through, one per run, once every section has been shown.": "Växlas igenom, ett per körning, när alla avsnitt har visats.",
	"Section %d": "Avsnitt %d",
	"How long before the next section can start.": "Hur länge innan nästa avsnitt kan börja.",
	"Write text here...": "Skriv text här...",

	"+ Add Section": "+ Lägg till avsnitt",
	"+ Add Response": "+ Lägg till svar",
	"+ Add Text": "+ Lägg till text",
	"Section Transition Delay": "Fördröjning mellan avsnitt",
	"Duration": "Längd",
	"Delay": "Fördröjning",
	"Alpha": "Alfa",
	"Font": "Typsnitt",
	"Text Size": "Textstorlek",
	"Text Color": "Textfärg",
	"Outline Size": "Konturstorlek",
	"Outline Color": "Konturfärg",
	"Shadow Size": "Skuggstorlek",
	"Shadow Offset": "Skuggförskjutning",
	"Shadow Color": "Skuggfärg",
	"Panel Behind Text": "Panel bakom text",
	"Panel Color": "Panelfärg",

	# Categories
	"Events": "Händelser",
	"Actions": "Handlingar",
	"Flow": "Flöde",

	# Node names
	"On Ready": "När scenen startar",
	"On Every Frame": "Varje bildruta",
	"On Input Action": "Vid inmatningsåtgärd",
	"On Button Pressed": "När en knapp trycks",
	"On Body or Area Entered": "När något rör mig",
	"On Body or Area Exited": "När något slutar röra mig",
	"On Timer Timeout": "När timern går ut",
	"On Signal": "Vid signal",
	"On Clicked": "Vid klick",
	"Juicy Button": "Saftig knapp",
	"On Died": "När jag dör",
	"Move": "Rör dig",
	"Jump": "Hoppa",
	"Launch": "Skjut iväg",
	"Fly": "Flyg",
	"Motor": "Motor",
	"Gravity": "Gravitation",
	"Animation": "Animation",
	"Character Animation": "Figuranimation",
	"Play Sound": "Spela ljud",
	"Spawn Scene": "Skapa scen",
	"Change Scene": "Byt scen",
	"Quit Game": "Avsluta spelet",
	"Visibility": "Synlighet",
	"Point Where Moving": "Peka dit du rör dig",
	"Rotate": "Rotera",
	"Print": "Skriv ut",
	"Show Text": "Visa text",
	"Send Signal": "Skicka signal",
	"Destroy": "Förstör",
	"Remember": "Kom ihåg",
	"Health": "Hälsa",
	"Set Property": "Sätt egenskap",
	"Set Color": "Sätt färg",
	"Wait": "Vänta",
	"Only If": "Bara om",
	"Wait Until": "Vänta tills",
	"Repeat": "Upprepa",
	"Random": "Slump",

	# Param labels
	"Acceleration": "Acceleration",
	"Action": "Åtgärd",
	"Amount": "Mängd",
	"Attack": "Attack",
	"Attack When": "Attack när",
	"Backward": "Bakåt",
	"Button": "Knapp",
	"Change Colors": "Ändra färger",
	"Click Grow": "Klickväxt",
	"Click Tilt": "Klicklutning",
	"Click Wiggle": "Klickvickning",
	"Color": "Färg",
	"Count": "Antal",
	"Coyote Seconds": "Prärievargsekunder",
	"Coyote Time": "Prärievargtid",
	"Crouch": "Huka",
	"Crouch Button": "Hukknapp",
	"Dead Idle": "Död vila",
	"Deceleration": "Inbromsning",
	"Die": "Dö",
	"Die When": "Dö när",
	"Direction": "Riktning",
	"Down Angle": "Nervinkel",
	"Drive": "Drivning",
	"Falling": "Faller",
	"Flip To Face": "Vänd åt rätt håll",
	"Forward": "Framåt",
	"From": "Från",
	"Game Type": "Speltyp",
	"Height": "Höjd",
	"Hover Color": "Hovringsfärg",
	"Hover Grow": "Hovringsväxt",
	"Hover Tilt": "Hovringslutning",
	"Hover Wiggle": "Hovringsvickning",
	"Hurt": "Skadad",
	"Hurt When": "Skadad när",
	"Idle": "Vila",
	"Interact": "Interagera",
	"Interact When": "Interagera när",
	"Invincible Seconds": "Osårbara sekunder",
	"Joint": "Led",
	"Kind": "Sort",
	"Label": "Etikett",
	"Landing": "Landar",
	"Layer": "Lager",
	"Limit Top Speed": "Begränsa toppfart",
	"Listen For": "Lyssna efter",
	"Max Speed": "Toppfart",
	"Mode": "Läge",
	"Normal Color": "Normal färg",
	"Only Named": "Endast namngiven",
	"Power": "Kraft",
	"Pressed Color": "Nedtryckt färg",
	"Property": "Egenskap",
	"Push": "Tryck",
	"Ramp": "Färgskala",
	"Run Blocks": "Kör block",
	"Save As": "Spara som",
	"Scene": "Scen",
	"Scope": "Omfång",
	"Seconds": "Sekunder",
	"Selected Color": "Vald färg",
	"Show My Name": "Visa mitt namn",
	"Show What Touched Me": "Visa vad som rörde mig",
	"Signal Name": "Signalnamn",
	"Sound": "Ljud",
	"Speed": "Fart",
	"Spin": "Snurr",
	"Strength": "Styrka",
	"Target": "Mål",
	"Test": "Test",
	"Tilt": "Lutning",
	"Tilt Back": "Luta bakåt",
	"Tilt Body": "Lutningskropp",
	"Tilt Forward": "Luta framåt",
	"Transparency": "Genomskinlighet",
	"Turn Speed": "Vändhastighet",
	"Up Angle": "Uppvinkel",
	"Use Color Ramp": "Använd färgskala",
	"Value": "Värde",
	"Variable Name": "Variabelnamn",
	"Volume": "Volym",
	"Wait To Finish": "Vänta tills klar",
	"Walk": "Gå",
	"Walk Down": "Gå ner",
	"Walk Left": "Gå vänster",
	"Walk Right": "Gå höger",
	"Walk Up": "Gå upp",

	# Headers inside nodes
	"ON HOVER": "VID HOVRING",
	"ON CLICK": "VID KLICK",
	"COLORS": "FÄRGER",
	"SET UP": "INSTÄLLNING",
	"MOVING": "RÖRELSE",
	"IN THE AIR": "I LUFTEN",
	"CROUCHING": "HUKANDE",
	"ONE-SHOT ACTIONS": "ENGÅNGSHANDLINGAR",
	"DYING": "DÖENDE",

	# Dropdown choices
	"None": "Ingen",
	"Space": "Mellanslag",
	"Enter": "Retur",
	"Tab": "Tabb",
	"Left": "Vänster",
	"Right": "Höger",
	"Up": "Upp",
	"Down": "Ner",
	"Mouse Left": "Mus vänster",
	"Mouse Right": "Mus höger",
	"Mouse Middle": "Mus mitten",
	"Anything": "Vad som helst",
	"Bodies only": "Bara kroppar",
	"Areas only": "Bara områden",
	"Where I'm facing": "Dit jag tittar",
	"Where I'm pointing": "Dit jag pekar",
	"Body": "Kropp",
	"Wheel joint": "Hjulled",
	"Whole game": "Hela spelet",
	"This node only": "Bara den här noden",
	"Set to": "Sätt till",
	"Add": "Lägg till",
	"Subtract": "Dra ifrån",
	"Keep highest": "Behåll högsta",
	"Set max": "Sätt max",
	"Damage": "Skada",
	"Heal": "Läk",
	"On": "På",
	"Off": "Av",
	"is On": "är På",
	"is Off": "är Av",
	"equals": "är lika med",
	"is not": "är inte",
	"is at least": "är minst",
	"is at most": "är högst",
	"is more than": "är mer än",
	"is less than": "är mindre än",
	"Text": "Text",
	"Show": "Visa",
	"Hide": "Göm",
	"Toggle": "Växla",
	"On me": "På mig",
	"At a node": "Vid en nod",
	"Side view": "Sidovy",
	"Top down": "Uppifrån",
	"Stop": "Stoppa",
	"Pause": "Pausa",
	"Resume": "Fortsätt",
	"Turn on": "Slå på",
	"Turn off": "Slå av",
	"Face direction": "Peka åt färdriktningen",
	"Lean": "Luta",
	"When pressed": "När den trycks",
	"While held": "Medan den hålls",
	"When released": "När den släpps",
	"Size": "Storlek",
	"Rotation": "Rotation",
}


static func t(text: String) -> String:
	return text if language == ENGLISH else SV.get(text, text)
